# Generated by Django 5.0.7 on 2024-07-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
