# Generated by Django 5.0.7 on 2024-07-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0002_alter_blogpost_deleted_at_alter_comment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
