# Generated by Django 5.0.7 on 2024-07-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0007_alter_blogpost_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
