# Generated by Django 5.0.7 on 2024-07-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0008_remove_blogpost_deleted_at_remove_comment_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
    ]
