# Generated by Django 5.0.7 on 2024-07-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0009_rename_is_deleted_blogpost_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postApp.blogpost'),
        ),
    ]
