# Generated by Django 5.0.7 on 2024-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0010_alter_comment_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
