# Generated by Django 5.0.7 on 2024-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0011_alter_reaction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='postApp.hashtag'),
        ),
    ]
